name:                distiller
version:             0.1.0
github:              "AliasQli/distiller"
license:             modified BSD3
author:              "Alias Qli"
maintainer:          "2576814881@qq.com"
copyright:           "2021 Alias Qli"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/AliasQli/distiller#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- random
- serialise
- text
- vector

ghc-options:
- -j
- -O
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-orphans
- -Wno-partial-type-signatures
- -Wno-unused-do-bind

default-extensions: 
- ApplicativeDo
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- PackageImports
- PartialTypeSignatures
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

library:
  source-dirs: src

executables:
  distiller:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distiller
